name: "Validate devcontainer-feature.json files"
on:
  # only run if CI - Test Features workflow is successful
  workflow_run:
    workflows: ["CI - Test Features"]
    if: github.event.workflow_run.conclusion == 'success'
    branches: ["main"]
    types:
      - completed
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
